name = "mcp-weather"
main = "src/worker.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# KV namespace for OAuth data
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "75e602d838ce4b0083aaf6ff8ae169b8"
preview_id = "1dc00692a48f43c9a136051541ce0ee0"

[env.production]
name = "mcp-weather-prod"
[[env.production.kv_namespaces]]
binding = "OAUTH_KV"
id = "75e602d838ce4b0083aaf6ff8ae169b8"

[env.staging]
name = "mcp-weather-staging" 
[[env.staging.kv_namespaces]]
binding = "OAUTH_KV"
id = "75e602d838ce4b0083aaf6ff8ae169b8" 